name: New Environment
values:
  - key: id
    value: ''
  - key: phone
    value: ''
  - key: password
    value: ''
  - key: firstName
    value: ''
  - key: lastName
    value: ''
  - key: username
    value: ''
  - key: email
    value: ''
  - key: userStatus
    value: ''
