name: Run Postman Tests

on:
  push:

jobs:
  postman-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Newman
        run: npm install -g newman

      - name: Run collection
        run: newman run PetStore.postman_collection.json \
  -e QA.postman_environment.json