name: Run Postman Tests

on:
  push:
  workflow_dispatch:

jobs:
  postman-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Newman
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      - name: Create reports folder
        run: mkdir reports

      - name: Run collection
        run: |
          newman run PetStore.postman_collection.json \
          -e QA.postman_environment.json \
          -r cli,json,htmlextra \
          --reporter-json-export reports/report.json \
          --reporter-htmlextra-export reports/report-$(date +%s).html

      - name: Upload Reports
        uses: actions/upload-artifact@v4
        with:
          name: newman-reports
          path: reports/